#!/usr/bin/env python3

###
# Generates build files for Project The Maybe(Not) Last Story (TrueEnding).
#
# Usage:
#   python configure.py
#   ninja
###

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

from tools.project import (
    Object,
    ProgressCategory,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

DEFAULT_VERSION = 0
VERSIONS = [
    "SLSEXJ",  # The Last Story (USA)
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    default=Path("build/compilers"),
    help="path to compilers",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

config.build_dir = args.build_dir
config.compilers_path = args.compilers
config.generate_map = args.map
config.non_matching = args.non_matching
config.dtk_path = Path("tools/dtk.exe")
config.objdiff_path = Path("tools/objdiff-cli.exe")

# Toolchain versions
config.binutils_tag = "2.42-1"
config.compilers_tag = "20240706"
config.dtk_tag = "v1.8.4"
config.objdiff_tag = "v3.8.1"
config.sjiswrap_tag = "v1.2.0"
config.linker_version = "Wii/1.0"  # Metrowerks CodeWarrior 4.3 build 145

# Project paths
config.config_path = Path("config.yml")
config.dol_path = Path("orig/main.dol")
config.check_sha_path = Path("orig/main.dol.sha1")
config.ldscript = Path("asm/ldscript.lcf")
config.ldflags = ["-fp hard", "-nodefaults"]
config.shift_jis = False

# Base C/C++ compiler flags (CodeWarrior 4.3 build 145)
cflags_base = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hard",
    "-O4,p",
    "-inline auto",
    "-Cpp_exceptions on",
    "-RTTI off",
    "-sdata 48",
    "-sdata2 48",
    "-i ./include",
    "-i ./src",
]

# Base C/C++ compiler flags for OS library
cflags_os = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hard",
    "-O4,p",
    "-inline auto",
    "-Cpp_exceptions on",
    "-RTTI off",
    "-sdata 8",
    "-sdata2 8",
    "-i ./include",
    "-i ./src",
]

config.cflags = cflags_base

# Registered libraries and translation units
config.libs = [
    {
        "lib": "Game",
        "mw_version": "Wii/1.0",
        "cflags": cflags_base,
        "objects": [
            Object(True, "entry.c"),
            Object(True, "game_init.c"),
            Object(True, "game_scene.c"),
            Object(True, "game_system.c"),
            Object(True, "game_manager.c"),
            Object(True, "game_actor.c"),
            Object(True, "game_battle.c"),
            Object(True, "game_entity.c"),
            Object(True, "game_property.c"),
            Object(True, "game_camera.c"),
            Object(True, "game_stage.c"),
            Object(True, "game_collision.c"),
            Object(True, "game_physics.c"),
            Object(True, "game_action.c"),
            Object(True, "game_event.c"),
            Object(True, "game_state.c"),
            Object(True, "game_effect.c"),
            Object(True, "game_ui.c"),
            Object(True, "game_menu.c"),
            Object(True, "game_sound.c"),
            Object(True, "game_item.c"),
            Object(True, "game_player.c"),
            Object(True, "game_ai.c"),
            Object(True, "game_path.c"),
            Object(True, "game_mission.c"),
            Object(True, "game_quest.c"),
            Object(True, "game_talk.c"),
            Object(True, "game_party.c"),
            Object(True, "game_equip.c"),
            Object(True, "game_skill.c"),
            Object(True, "game_magic.c"),
            Object(True, "game_enemy.c"),
            Object(True, "game_boss.c"),
            Object(True, "game_gimmick.c"),
            Object(True, "game_script.c"),
            Object(True, "game_sequence.c"),
            Object(True, "game_chapter.c"),
            Object(True, "game_scenario.c"),
            Object(True, "game_dialogue.c"),
            Object(True, "game_cutscene.c"),
            Object(True, "game_cinema.c"),
            Object(True, "game_world.c"),
            Object(True, "game_dungeon.c"),
            Object(True, "game_town.c"),
            Object(True, "game_field.c"),
            Object(True, "game_nav.c"),
            Object(True, "game_route.c"),
            Object(True, "game_zone.c"),
            Object(True, "game_area.c"),
            Object(True, "game_map.c"),
            Object(True, "game_minimap.c"),
            Object(True, "game_marker.c"),
            Object(True, "game_radar.c"),
            Object(True, "game_compass.c"),
            Object(True, "game_target.c"),
            Object(True, "game_lockon.c"),
            Object(True, "game_cursor.c"),
            Object(True, "game_focus.c"),
            Object(True, "game_reticle.c"),
            Object(True, "game_hud.c"),
            Object(True, "game_gauge.c"),
            Object(True, "game_meter.c"),
            Object(True, "game_font.c"),
            Object(True, "game_msg.c"),
            Object(True, "game_window.c"),
            Object(True, "game_cursor_ui.c"),
            Object(True, "game_layout.c"),
            Object(True, "game_pane.c"),
            Object(True, "game_textbox.c"),
            Object(True, "game_graphic.c"),
            Object(True, "game_render_ui.c"),
            Object(True, "game_draw_2d.c"),
            Object(True, "game_sprite.c"),
            Object(True, "game_texture.c"),
            Object(True, "game_material.c"),
            Object(True, "game_shader.c"),
            Object(True, "game_mesh.c"),
            Object(True, "game_model.c"),
            Object(True, "game_motion.c"),
            Object(True, "game_skeleton.c"),
            Object(True, "game_skin.c"),
            Object(True, "game_joint.c"),
            Object(True, "game_ik.c"),
            Object(True, "game_cluster.c"),
            Object(True, "game_morph.c"),
            Object(True, "game_rig.c"),
            Object(True, "game_light.c"),
            Object(True, "game_shadow.c"),
            Object(True, "game_fog.c"),
            Object(True, "game_postfx.c"),
            Object(True, "game_bloom.c"),
            Object(True, "game_depth.c"),
            Object(True, "game_occ.c"),
            Object(True, "game_cull.c"),
            Object(True, "game_env.c"),
            Object(True, "game_sky.c"),
            Object(True, "game_water.c"),
            Object(True, "game_particle.c"),
            Object(True, "game_emitter.c"),
            Object(True, "game_flare.c"),
            Object(True, "game_decal.c"),
            Object(True, "game_weather.c"),
            Object(True, "game_wind.c"),
            Object(True, "game_sound_fx.c"),
            Object(True, "game_cam_mode.c"),
            Object(True, "game_cam_spline.c"),
            Object(True, "game_view.c"),
            Object(True, "game_frustum.c"),
            Object(True, "game_projection.c"),
            Object(True, "game_viewport.c"),
            Object(True, "game_scissor.c"),
            Object(True, "game_clip.c"),
            Object(True, "game_transform.c"),
            Object(True, "game_bounding.c"),
            Object(True, "game_collision_3d.c"),
            Object(True, "game_collision_mesh.c"),
            Object(True, "game_collision_octree.c"),
            Object(True, "game_collision_bsp.c"),
            Object(True, "game_collision_query.c"),
            Object(True, "game_hitbox.c"),
            Object(True, "game_hurtbox.c"),
            Object(True, "game_phys_rigid.c"),
            Object(True, "game_phys_spring.c"),
            Object(True, "game_phys_cloth.c"),
            Object(True, "game_phys_rope.c"),
            Object(True, "game_phys_ragdoll.c"),
            Object(True, "game_phys_world.c"),
            Object(True, "game_actor_base.c"),
            Object(True, "game_actor_manager.c"),
            Object(True, "game_actor_spawn.c"),
            Object(True, "game_actor_state.c"),
            Object(True, "game_player_move.c"),
            Object(True, "game_player_action.c"),
            Object(True, "game_player_anim.c"),
            Object(True, "game_player_combat.c"),
            Object(True, "game_player_skill.c"),
            Object(True, "game_player_equip.c"),
            Object(True, "game_player_magic.c"),
            Object(True, "game_player_status.c"),
            Object(True, "game_enemy_base.c"),
            Object(True, "game_enemy_ai.c"),
            Object(True, "game_enemy_path.c"),
            Object(True, "game_enemy_nav.c"),
            Object(True, "game_enemy_anim.c"),
            Object(True, "game_enemy_attack.c"),
            Object(True, "game_enemy_spawn.c"),
            Object(True, "game_boss_base.c"),
            Object(True, "game_boss_ai.c"),
            Object(True, "game_boss_phase.c"),
            Object(True, "game_boss_action.c"),
            Object(True, "game_npc_base.c"),
            Object(True, "game_npc_ai.c"),
            Object(True, "game_npc_state.c"),
            Object(True, "game_npc_talk.c"),
            Object(True, "game_quest_mgr.c"),
            Object(True, "game_quest_data.c"),
            Object(True, "game_quest_flow.c"),
            Object(True, "game_quest_reward.c"),
            Object(True, "game_dialog_box.c"),
            Object(True, "game_dialog_script.c"),
            Object(True, "game_dialog_choice.c"),
            Object(True, "game_dialog_event.c"),
            Object(True, "game_inventory_base.c"),
            Object(True, "game_inventory_item.c"),
            Object(True, "game_inventory_equip.c"),
            Object(True, "game_inventory_shop.c"),
            Object(True, "game_shop_buy.c"),
            Object(True, "game_shop_sell.c"),
            Object(True, "game_shop_craft.c"),
            Object(True, "game_shop_upgrade.c"),
            Object(True, "game_party_mgr.c"),
            Object(True, "game_party_member.c"),
            Object(True, "game_party_formation.c"),
            Object(True, "game_party_tactic.c"),
            Object(True, "game_battle_mgr.c"),
            Object(True, "game_battle_seq.c"),
            Object(True, "game_battle_calc.c"),
            Object(True, "game_battle_damage.c"),
            Object(True, "game_battle_buff.c"),
            Object(True, "game_battle_debuff.c"),
            Object(True, "game_battle_aggro.c"),
            Object(True, "game_battle_camera.c"),
            Object(True, "game_battle_ui.c"),
            Object(True, "game_battle_result.c"),
            Object(True, "game_battle_exp.c"),
            Object(True, "game_battle_drop.c"),
            Object(True, "game_map_world.c"),
            Object(True, "game_map_area.c"),
            Object(True, "game_map_zone.c"),
            Object(True, "game_map_dungeon.c"),
            Object(True, "game_map_collision.c"),
            Object(True, "game_map_object.c"),
            Object(True, "game_map_interact.c"),
            Object(True, "game_map_gimmick.c"),
            Object(True, "game_map_door.c"),
            Object(True, "game_map_chest.c"),
            Object(True, "game_map_trap.c"),
            Object(True, "game_map_elevator.c"),
            Object(True, "game_map_ladder.c"),
            Object(True, "game_map_water_flow.c"),
            Object(True, "game_map_stream.c"),
            Object(True, "game_map_light_zone.c"),
            Object(True, "game_stage_mgr.c"),
            Object(True, "game_stage_load.c"),
            Object(True, "game_stage_unload.c"),
            Object(True, "game_stage_transition.c"),
            Object(True, "game_stage_state.c"),
            Object(True, "game_stage_event.c"),
            Object(True, "game_stage_bgm.c"),
            Object(True, "game_stage_se.c"),
            Object(True, "game_scene_mgr.c"),
            Object(True, "game_scene_title.c"),
            Object(True, "game_scene_menu.c"),
            Object(True, "game_scene_camp.c"),
            Object(True, "game_scene_town.c"),
            Object(True, "game_scene_dungeon.c"),
            Object(True, "game_scene_battle.c"),
            Object(True, "game_scene_event.c"),
            Object(True, "game_scene_ending.c"),
            Object(True, "game_scene_gameover.c"),
            Object(True, "game_ui_menu_main.c"),
            Object(True, "game_ui_menu_item.c"),
            Object(True, "game_ui_menu_equip.c"),
            Object(True, "game_ui_menu_skill.c"),
            Object(True, "game_ui_menu_status.c"),
            Object(True, "game_ui_menu_config.c"),
            Object(True, "game_ui_menu_save.c"),
            Object(True, "game_ui_hud_radar.c"),
            Object(True, "game_ui_hud_gauge.c"),
            Object(True, "game_ui_hud_target.c"),
            Object(True, "game_ui_hud_compass.c"),
            Object(True, "game_ui_hud_action.c"),
            Object(True, "game_ui_hud_prompt.c"),
            Object(True, "game_ui_hud_damage.c"),
            Object(True, "game_ui_hud_buff.c"),
            Object(True, "game_ui_hud_log.c"),
            Object(True, "game_ui_hud_subtitles.c"),
            Object(True, "game_ui_hud_minimap.c"),
            Object(True, "game_ui_hud_crosshair.c"),
            Object(True, "game_sound_stream.c"),
            Object(True, "game_sound_voice.c"),
            Object(True, "game_sound_ambient.c"),
            Object(True, "game_sound_bus.c"),
            Object(True, "game_sound_dsp.c"),
            Object(True, "game_sound_reverb.c"),
            Object(True, "game_sound_filter.c"),
            Object(True, "game_sound_cue.c"),
            Object(True, "game_net_manager.c"),
            Object(True, "game_net_packet.c"),
            Object(True, "game_net_session.c"),
            Object(True, "game_net_lobby.c"),
            Object(True, "game_net_sync.c"),
            Object(True, "game_net_player.c"),
            Object(True, "game_net_match.c"),
            Object(True, "game_net_rank.c"),
            Object(True, "game_save_header.c"),
            Object(True, "game_save_slot.c"),
            Object(True, "game_save_crc.c"),
            Object(True, "game_save_backup.c"),
            Object(True, "game_system_heap.c"),
            Object(True, "game_system_alloc.c"),
            Object(True, "game_system_thread.c"),
            Object(True, "game_system_clock.c"),
            Object(True, "game_system_profile.c"),
            Object(True, "game_system_perf.c"),
            Object(True, "game_system_log.c"),
            Object(True, "game_system_assert.c"),
            Object(True, "game_system_memory.c"),
            Object(True, "game_system_string.c"),
            Object(True, "game_system_math.c"),
            Object(True, "game_system_random.c"),
            Object(True, "game_system_timer.c"),
            Object(True, "game_system_event.c"),
            Object(True, "game_system_message.c"),
            Object(True, "game_system_callback.c"),
            Object(True, "game_sys_task_mgr.c"),
            Object(True, "game_sys_task_worker.c"),
            Object(True, "game_sys_task_queue.c"),
            Object(True, "game_sys_thread_pool.c"),
            Object(True, "game_sys_file_loader.c"),
            Object(True, "game_sys_file_cache.c"),
            Object(True, "game_sys_file_stream.c"),
            Object(True, "game_sys_file_archive.c"),
            Object(True, "game_res_manager.c"),
            Object(True, "game_res_package.c"),
            Object(True, "game_res_loader.c"),
            Object(True, "game_res_unpacker.c"),
            Object(True, "game_res_texture.c"),
            Object(True, "game_res_model.c"),
            Object(True, "game_res_motion.c"),
            Object(True, "game_res_sound.c"),
            Object(True, "game_res_effect.c"),
            Object(True, "game_res_font.c"),
            Object(True, "game_res_msg.c"),
            Object(True, "game_res_layout.c"),
            Object(True, "game_res_shader.c"),
            Object(True, "game_res_material.c"),
            Object(True, "game_res_collision.c"),
            Object(True, "game_res_stage.c"),
            Object(True, "game_script_engine.c"),
            Object(True, "game_script_vm.c"),
            Object(True, "game_script_opcodes.c"),
            Object(True, "game_script_stack.c"),
            Object(True, "game_script_vars.c"),
            Object(True, "game_script_tables.c"),
            Object(True, "game_script_events.c"),
            Object(True, "game_script_coroutine.c"),
            Object(True, "game_script_thread.c"),
            Object(True, "game_script_debug.c"),
            Object(True, "game_script_native.c"),
            Object(True, "game_script_compiler.c"),
            Object(True, "game_ai_tree_root.c"),
            Object(True, "game_ai_tree_node.c"),
            Object(True, "game_ai_tree_branch.c"),
            Object(True, "game_ai_tree_leaf.c"),
            Object(True, "game_ai_blackboard.c"),
            Object(True, "game_ai_perception.c"),
            Object(True, "game_ai_memory.c"),
            Object(True, "game_ai_decision.c"),
            Object(True, "game_ai_steering.c"),
            Object(True, "game_ai_formation.c"),
            Object(True, "game_ai_tactics.c"),
            Object(True, "game_ai_squad.c"),
            Object(True, "game_anim_blend_tree.c"),
            Object(True, "game_anim_blend_node.c"),
            Object(True, "game_anim_layer.c"),
            Object(True, "game_anim_mask.c"),
            Object(True, "game_anim_track.c"),
            Object(True, "game_anim_event.c"),
            Object(True, "game_anim_notify.c"),
            Object(True, "game_anim_warp.c"),
            Object(True, "game_cloth_sim.c"),
            Object(True, "game_cloth_mesh.c"),
            Object(True, "game_cloth_collision.c"),
            Object(True, "game_cloth_constraint.c"),
            Object(True, "game_fx_particle_mgr.c"),
            Object(True, "game_fx_particle_system.c"),
            Object(True, "game_fx_emitter_point.c"),
            Object(True, "game_fx_emitter_box.c"),
            Object(True, "game_fx_emitter_sphere.c"),
            Object(True, "game_fx_emitter_mesh.c"),
            Object(True, "game_fx_ribbon.c"),
            Object(True, "game_fx_trail.c"),
            Object(True, "game_fx_beam.c"),
            Object(True, "game_fx_distortion.c"),
            Object(True, "game_fx_heat_haze.c"),
            Object(True, "game_fx_shockwave.c"),
            Object(True, "game_fx_explosion.c"),
            Object(True, "game_fx_smoke.c"),
            Object(True, "game_fx_fire.c"),
            Object(True, "game_fx_sparks.c"),
            Object(True, "game_fx_debris.c"),
            Object(True, "game_fx_lightning.c"),
            Object(True, "game_fx_magic_circle.c"),
            Object(True, "game_fx_aura.c"),
            Object(True, "game_render_pipeline.c"),
            Object(True, "game_render_pass.c"),
            Object(True, "game_render_queue.c"),
            Object(True, "game_render_sort.c"),
            Object(True, "game_render_batch.c"),
            Object(True, "game_render_instancing.c"),
            Object(True, "game_render_culling.c"),
            Object(True, "game_render_occlusion.c"),
            Object(True, "game_render_shadow_map.c"),
            Object(True, "game_render_depth_prepass.c"),
            Object(True, "game_render_forward.c"),
            Object(True, "game_render_deferred.c"),
            Object(True, "game_render_translucent.c"),
            Object(True, "game_render_composite.c"),
            Object(True, "game_render_bloom_pass.c"),
            Object(True, "game_render_tone_map.c"),
            Object(True, "game_post_dof.c"),
            Object(True, "game_post_motion_blur.c"),
            Object(True, "game_post_color_correct.c"),
            Object(True, "game_post_lut.c"),
            Object(True, "game_post_vignette.c"),
            Object(True, "game_post_film_grain.c"),
            Object(True, "game_post_radial_blur.c"),
            Object(True, "game_post_chromatic.c"),
            Object(True, "game_post_lens_flare.c"),
            Object(True, "game_post_sun_shafts.c"),
            Object(True, "game_post_fxaa.c"),
            Object(True, "game_post_ssao.c"),
            Object(True, "game_post_ssr.c"),
            Object(True, "game_post_fog_volume.c"),
            Object(True, "game_post_heat_wave.c"),
            Object(True, "game_post_underwater.c"),
            Object(True, "game_camera_shake.c"),
            Object(True, "game_camera_fov.c"),
            Object(True, "game_camera_collision.c"),
            Object(True, "game_camera_target.c"),
            Object(True, "game_camera_cinematic.c"),
            Object(True, "game_camera_follow.c"),
            Object(True, "game_camera_free.c"),
            Object(True, "game_camera_orbit.c"),
            Object(True, "game_input_buffer.c"),
            Object(True, "game_input_combo.c"),
            Object(True, "game_input_gesture.c"),
            Object(True, "game_input_deadzone.c"),
            Object(True, "game_input_rumble.c"),
            Object(True, "game_input_cursor.c"),
            Object(True, "game_input_virtual_pad.c"),
            Object(True, "game_input_remap.c"),
            Object(True, "game_audio_mixer.c"),
            Object(True, "game_audio_channel.c"),
            Object(True, "game_audio_streamer.c"),
            Object(True, "game_audio_emitter.c"),
            Object(True, "game_audio_spatial.c"),
            Object(True, "game_audio_voice_mgr.c"),
            Object(True, "game_audio_voice_bank.c"),
            Object(True, "game_audio_voice_track.c"),
            Object(True, "game_audio_voice_sync.c"),
            Object(True, "game_audio_music_mgr.c"),
            Object(True, "game_audio_music_bank.c"),
            Object(True, "game_audio_music_cross.c"),
            Object(True, "game_audio_music_tempo.c"),
            Object(True, "game_audio_sfx_mgr.c"),
            Object(True, "game_audio_sfx_group.c"),
            Object(True, "game_audio_sfx_pitch.c"),
            Object(True, "game_audio_sfx_limit.c"),
            Object(True, "game_audio_env_reverb.c"),
            Object(True, "game_audio_env_echo.c"),
            Object(True, "game_audio_env_occlude.c"),
            Object(True, "game_audio_env_zone.c"),
            Object(True, "game_audio_3d_listener.c"),
            Object(True, "game_audio_3d_source.c"),
            Object(True, "game_audio_3d_cone.c"),
            Object(True, "game_audio_3d_doppler.c"),
            Object(True, "game_cutscene_director.c"),
            Object(True, "game_cutscene_track.c"),
            Object(True, "game_cutscene_actor.c"),
            Object(True, "game_cutscene_camera.c"),
            Object(True, "game_cutscene_event.c"),
            Object(True, "game_cutscene_audio.c"),
            Object(True, "game_cutscene_subtitle.c"),
            Object(True, "game_cutscene_fade.c"),
            Object(True, "game_cinematic_mgr.c"),
            Object(True, "game_cinematic_seq.c"),
            Object(True, "game_cinematic_shot.c"),
            Object(True, "game_cinematic_dof.c"),
            Object(True, "game_movie_player.c"),
            Object(True, "game_movie_decoder.c"),
            Object(True, "game_movie_render.c"),
            Object(True, "game_movie_audio.c"),
            Object(True, "game_system_save_data.c"),
            Object(True, "game_system_save_io.c"),
            Object(True, "game_system_save_crypt.c"),
            Object(True, "game_system_save_meta.c"),
            Object(True, "game_system_nand_mgr.c"),
            Object(True, "game_system_nand_file.c"),
            Object(True, "game_system_nand_dir.c"),
            Object(True, "game_system_nand_quota.c"),
            Object(True, "game_system_disc_mgr.c"),
            Object(True, "game_system_disc_read.c"),
            Object(True, "game_system_disc_seek.c"),
            Object(True, "game_system_disc_error.c"),
            Object(True, "game_system_memory_card.c"),
            Object(True, "game_system_card_io.c"),
            Object(True, "game_system_card_sector.c"),
            Object(True, "game_system_card_format.c"),
            Object(True, "game_system_card_stat.c"),
            Object(True, "game_system_home_menu.c"),
            Object(True, "game_system_home_button.c"),
            Object(True, "game_system_home_render.c"),
            Object(True, "game_system_home_sound.c"),
            Object(True, "game_system_wpad_sync.c"),
            Object(True, "game_system_wpad_rumble.c"),
            Object(True, "game_system_wpad_motor.c"),
            Object(True, "game_system_wpad_speaker.c"),
            Object(True, "game_system_wpad_accel.c"),
            Object(True, "game_system_kpad_read.c"),
            Object(True, "game_system_kpad_calib.c"),
            Object(True, "game_system_kpad_clamp.c"),
            Object(True, "game_system_kpad_filter.c"),
            Object(True, "game_system_dvd_cache.c"),
            Object(True, "game_system_dvd_stream.c"),
            Object(True, "game_system_dvd_queue.c"),
            Object(True, "game_system_dvd_notify.c"),
            Object(True, "game_system_fat_mgr.c"),
            Object(True, "game_system_fat_cluster.c"),
            Object(True, "game_system_nwc24_mgr.c"),
            Object(True, "game_system_nwc24_dl.c"),
            Object(True, "game_system_nwc24_msg.c"),
            Object(True, "game_system_nwc24_data.c"),
            Object(True, "game_system_nwc24_secret.c"),
            Object(True, "game_system_nwc24_friend.c"),
            Object(True, "game_system_net_so.c"),
            Object(True, "game_system_net_ssl.c"),
            Object(True, "game_system_net_http.c"),
            Object(True, "game_system_net_dwc.c"),
            Object(True, "game_system_net_login.c"),
            Object(True, "game_system_net_auth.c"),
            Object(True, "game_system_net_ranking.c"),
            Object(True, "game_system_net_ghost.c"),
            Object(True, "game_system_net_coop.c"),
            Object(True, "game_system_net_versus.c"),
            Object(True, "game_system_net_room.c"),
            Object(True, "game_system_net_lobby_ui.c"),
            Object(True, "game_system_net_chat.c"),
            Object(True, "game_system_net_stats.c"),
            Object(True, "game_title_logo.c"),
            Object(True, "game_title_movie.c"),
            Object(True, "game_title_press_start.c"),
            Object(True, "game_title_main_menu.c"),
            Object(True, "game_title_new_game.c"),
            Object(True, "game_title_load_game.c"),
            Object(True, "game_title_options.c"),
            Object(True, "game_title_extras.c"),
            Object(True, "game_camp_menu_mgr.c"),
            Object(True, "game_camp_party_select.c"),
            Object(True, "game_camp_status_view.c"),
            Object(True, "game_camp_skill_assign.c"),
            Object(True, "game_camp_equip_change.c"),
            Object(True, "game_camp_item_use.c"),
            Object(True, "game_camp_craft_forge.c"),
            Object(True, "game_camp_dye_color.c"),
            Object(True, "game_camp_quest_log.c"),
            Object(True, "game_camp_encyclopedia.c"),
            Object(True, "game_camp_sound_test.c"),
            Object(True, "game_camp_system_save.c"),
            Object(True, "game_town_npc_manager.c"),
            Object(True, "game_town_crowd_ai.c"),
            Object(True, "game_town_market_stall.c"),
            Object(True, "game_town_tavern_event.c"),
            Object(True, "game_town_arena_lobby.c"),
            Object(True, "game_town_arena_fight.c"),
            Object(True, "game_town_castle_gate.c"),
            Object(True, "game_town_castle_courtyard.c"),
            Object(True, "game_town_alley_stealth.c"),
            Object(True, "game_town_rooftop_jump.c"),
            Object(True, "game_dungeon_room_mgr.c"),
            Object(True, "game_dungeon_door_lock.c"),
            Object(True, "game_dungeon_switch_puzzle.c"),
            Object(True, "game_dungeon_pressure_plate.c"),
            Object(True, "game_dungeon_torch_light.c"),
            Object(True, "game_dungeon_pit_fall.c"),
            Object(True, "game_dungeon_chest_loot.c"),
            Object(True, "game_dungeon_spawn_wave.c"),
            Object(True, "game_dungeon_barrier_field.c"),
            Object(True, "game_dungeon_boss_arena.c"),
            Object(True, "game_battle_tactics_order.c"),
            Object(True, "game_battle_gather_ring.c"),
            Object(True, "game_battle_heal_circle.c"),
            Object(True, "game_battle_slash_aim.c"),
            Object(True, "game_battle_sniper_cross.c"),
            Object(True, "game_battle_cover_vault.c"),
            Object(True, "game_battle_climb_beast.c"),
            Object(True, "game_battle_weakpoint.c"),
            Object(True, "game_battle_chain_attack.c"),
            Object(True, "game_battle_burst_gauge.c"),
            Object(True, "game_battle_spirit_drive.c"),
            Object(True, "game_battle_finish_blow.c"),
            Object(True, "game_battle_revive_ally.c"),
            Object(True, "game_battle_command_mode.c"),
            Object(True, "game_battle_slow_time.c"),
            Object(True, "game_battle_target_cursor.c"),
            Object(True, "game_battle_line_of_sight.c"),
            Object(True, "game_battle_cover_point.c"),
            Object(True, "game_battle_vault_kick.c"),
            Object(True, "game_battle_climb_aim.c"),
            Object(True, "game_battle_plunge_attack.c"),
            Object(True, "game_battle_parry_guard.c"),
            Object(True, "game_battle_dodge_roll.c"),
            Object(True, "game_battle_knockback_wall.c"),
            Object(True, "game_battle_terrain_hazard.c"),
            Object(True, "game_battle_water_conduct.c"),
            Object(True, "game_battle_ice_freeze.c"),
            Object(True, "game_battle_fire_diffuse.c"),
            Object(True, "game_battle_wind_disperse.c"),
            Object(True, "game_battle_light_holy.c"),
            Object(True, "game_battle_dark_curse.c"),
            Object(True, "game_battle_element_chain.c"),
            Object(True, "game_battle_status_burn.c"),
            Object(True, "game_battle_status_freeze.c"),
            Object(True, "game_battle_status_paralyze.c"),
            Object(True, "game_battle_status_sleep.c"),
            Object(True, "game_battle_status_silence.c"),
            Object(True, "game_battle_status_daze.c"),
            Object(True, "game_battle_ai_zael.c"),
            Object(True, "game_battle_ai_calista.c"),
            Object(True, "game_battle_ai_dagran.c"),
            Object(True, "game_battle_ai_syrenne.c"),
            Object(True, "game_battle_ai_lowell.c"),
            Object(True, "game_battle_ai_mirania.c"),
            Object(True, "game_battle_ai_yurick.c"),
            Object(True, "game_battle_ai_general.c"),
            Object(True, "game_gmk_item_slot.c"),
            Object(True, "game_gmk_slot_anime.c"),
            Object(True, "game_gmk_slot_cache.c"),
            Object(True, "game_gmk_slot_draw.c"),
            Object(True, "game_gmk_slot_event.c"),
            Object(True, "game_gmk_slot_trigger.c"),
            Object(True, "game_boss_cocoon_init.c"),
            Object(True, "game_boss_cocoon_state.c"),
            Object(True, "game_boss_cocoon_move.c"),
            Object(True, "game_boss_cocoon_anim.c"),
            Object(True, "game_boss_cocoon_action.c"),
            Object(True, "game_boss_cocoon_ai.c"),
            Object(True, "game_boss_cocoon_skill.c"),
            Object(True, "game_boss_cocoon_damage.c"),
            Object(True, "game_boss_cocoon_rage.c"),
            Object(True, "game_boss_cocoon_laser.c"),
            Object(True, "game_boss_cocoon_sub.c"),
            Object(True, "game_boss_cocoon_phase2.c"),
            Object(True, "game_boss_cocoon_phase3.c"),
            Object(True, "game_boss_cocoon_tail.c"),
            Object(True, "game_boss_cocoon_claw.c"),
            Object(True, "game_boss_cocoon_roar.c"),
            Object(True, "game_boss_cocoon_death.c"),
            Object(True, "game_boss_cocoon_fx.c"),
            Object(True, "game_boss_cocoon_shield.c"),
            Object(True, "game_boss_cocoon_weak.c"),
            Object(True, "game_boss_cocoon_laser_aim.c"),
            Object(True, "game_boss_cocoon_spin.c"),
            Object(True, "game_boss_cocoon_rush.c"),
            Object(True, "game_boss_cocoon_shockwave.c"),
            Object(True, "game_event_cutscene_mgr.c"),
            Object(True, "game_event_cutscene_cam.c"),
            Object(True, "game_event_cutscene_actor.c"),
            Object(True, "game_event_cutscene_voice.c"),
            Object(True, "game_event_cutscene_fade.c"),
            Object(True, "game_event_cutscene_skip.c"),
            Object(True, "game_quest_sub_mgr.c"),
            Object(True, "game_quest_sub_stage.c"),
            Object(True, "game_quest_sub_target.c"),
            Object(True, "game_quest_sub_reward.c"),
            Object(True, "game_quest_sub_dialog.c"),
            Object(True, "game_quest_sub_complete.c"),
            Object(True, "game_coliseum_mgr.c"),
            Object(True, "game_coliseum_round.c"),
            Object(True, "game_coliseum_enemy.c"),
            Object(True, "game_coliseum_score.c"),
            Object(True, "game_coliseum_reward.c"),
            Object(True, "game_coliseum_ranking.c"),
            Object(True, "game_net_lobby_mgr.c"),
            Object(True, "game_net_lobby_room.c"),
            Object(True, "game_net_lobby_match.c"),
            Object(True, "game_net_lobby_player.c"),
            Object(True, "game_net_lobby_sync.c"),
            Object(True, "game_net_lobby_chat.c"),
            Object(True, "game_net_coop_mgr.c"),
            Object(True, "game_net_coop_session.c"),
            Object(True, "game_net_coop_spawn.c"),
            Object(True, "game_net_coop_boss.c"),
            Object(True, "game_net_coop_drop.c"),
            Object(True, "game_net_coop_score.c"),
            Object(True, "game_net_packet_mgr.c"),
            Object(True, "game_net_packet_queue.c"),
            Object(True, "game_net_crypt_core.c"),
            Object(True, "game_net_crypt_key.c"),
            Object(True, "game_net_crypt_cipher.c"),
            Object(True, "game_net_crypt_auth.c"),
            Object(True, "game_net_versus_mgr.c"),
            Object(True, "game_net_versus_rule.c"),
            Object(True, "game_net_versus_map.c"),
            Object(True, "game_net_versus_stat.c"),
            Object(True, "game_net_versus_leader.c"),
            Object(True, "game_net_versus_award.c"),
            Object(True, "game_net_replay_mgr.c"),
            Object(True, "game_net_replay_data.c"),
            Object(True, "game_net_replay_play.c"),
            Object(True, "game_net_sync_clock.c"),
            Object(True, "game_net_sync_state.c"),
            Object(True, "game_net_sync_event.c"),
            Object(True, "game_net_friend_mgr.c"),
            Object(True, "game_net_friend_list.c"),
            Object(True, "game_net_friend_invite.c"),
            Object(True, "game_net_voice_chat.c"),
            Object(True, "game_net_voice_codec.c"),
            Object(True, "game_net_voice_buffer.c"),
            Object(True, "game_flow_title_mgr.c"),
            Object(True, "game_flow_title_menu.c"),
            Object(True, "game_flow_title_logo.c"),
            Object(True, "game_flow_opening_movie.c"),
            Object(True, "game_flow_chapter_intro.c"),
            Object(True, "game_flow_chapter_outro.c"),
            Object(True, "game_flow_epilogue_mgr.c"),
            Object(True, "game_flow_credits_roll.c"),
            Object(True, "game_flow_credits_draw.c"),
            Object(True, "game_flow_clear_save.c"),
            Object(True, "game_flow_new_game_plus.c"),
            Object(True, "game_flow_gallery_mgr.c"),
        ],
    },
    {
        "lib": "Runtime",
        "mw_version": "Wii/1.0",
        "cflags": cflags_base,
        "objects": [
            Object(True, "__init_hardware.c"),
            Object(True, "memcpy.c"),
            Object(True, "memset.c"),
            Object(True, "global_destructor_chain.c"),
            Object(True, "__init_cpp_exceptions.cpp"),
            Object(True, "init_user.c"),
        ],
    },
    {
        "lib": "OS",
        "mw_version": "Wii/1.0",
        "cflags": cflags_os,
        "objects": [
            Object(True, "OSAlarm.c"),
            Object(True, "OSAlloc.c"),
            Object(True, "OSArena.c"),
            Object(True, "OSAudioSystem.c"),
            Object(True, "OSCache.c"),
            Object(True, "OSContext.c"),
            Object(True, "OSError.c"),
            Object(True, "OSExec.c"),
            Object(True, "OSFatal.c"),
            Object(True, "OSFont.c"),
            Object(True, "OSInterrupt.c"),
            Object(True, "OSModule.c"),
            Object(True, "OSMemory.c"),
            Object(True, "OSMutex.c"),
            Object(True, "OSReboot.c"),
            Object(True, "OSSram.c"),
            Object(True, "OSSystemCall.c"),
            Object(True, "OSThread.c"),
            Object(True, "OSTime.c"),
            Object(True, "OSIpc.c"),
            Object(True, "OSReset.c"),
            Object(True, "OSPlayTime.c"),
            Object(True, "OSTitle.c"),
            Object(True, "PSMTX.c"),
            Object(True, "mtx.c"),
            Object(True, "mtx44.c"),
            Object(True, "vec.c"),
            Object(True, "quat.c"),
            Object(True, "DVDFS.c"),
            Object(True, "dvd.c"),
            Object(True, "dvdqueue.c"),
            Object(True, "dvderror.c"),
            Object(True, "dvdFatal.c"),
            Object(True, "dvd_broadway.c"),
            Object(True, "vi3in1.c"),
            Object(True, "vi.c"),
            Object(True, "pad.c"),
            Object(True, "ai.c"),
            Object(True, "ax.c"),
            Object(True, "AXAlloc.c"),
            Object(True, "AXAux.c"),
            Object(True, "AXCL.c"),
            Object(True, "AXOut.c"),
            Object(True, "AXVPB.c"),
            Object(True, "AXSPB.c"),
            Object(True, "AXProf.c"),
            Object(True, "AXFXReverbHi.c"),
            Object(True, "AXFXReverbHiExp.c"),
            Object(True, "AXFXReverbStdExp.c"),
            Object(True, "AXFXDelay.c"),
            Object(True, "AXFXChorusExp.c"),
            Object(True, "AXFXReverbHiExpDpl2.c"),
            Object(True, "AXFXReverbStd.c"),
            Object(True, "AXFXReverbHiDpl2.c"),
            Object(True, "AXFXHooks.c"),
            Object(True, "dsp.c"),
            Object(True, "dsp_task.c"),
            Object(True, "GXInit.c"),
            Object(True, "GXFifo.c"),
            Object(True, "GXAttr.c"),
            Object(True, "GXMisc.c"),
            Object(True, "GXGeometry.c"),
            Object(True, "GXFrameBuf.c"),
            Object(True, "GXLight.c"),
            Object(True, "GXTexture.c"),
            Object(True, "GXBump.c"),
            Object(True, "GXTev.c"),
            Object(True, "GXPixel.c"),
            Object(True, "GXDisplayList.c"),
            Object(True, "isfs.c"),
            Object(True, "ipc.c"),
            Object(True, "ipcclt.c"),
            Object(True, "ipcprof.c"),
            Object(True, "nand.c"),
            Object(True, "NANDOpenClose.c"),
            Object(True, "NANDCheck.c"),
            Object(True, "NANDCore.c"),
            Object(True, "NANDLogging.c"),
            Object(True, "nanderror.c"),
            Object(True, "scsystem.c"),
            Object(True, "scapi.c"),
            Object(True, "hcis.c"),
            Object(True, "bta_sys.c"),
            Object(True, "bta_dm.c"),
            Object(True, "bta_hh.c"),
            Object(True, "btm_acl.c"),
            Object(True, "btm_dev.c"),
            Object(True, "btm_inq.c"),
            Object(True, "btm_sco.c"),
            Object(True, "btm_sec.c"),
            Object(True, "gap.c"),
            Object(True, "hid.c"),
            Object(True, "l2cap.c"),
            Object(True, "rfcomm.c"),
            Object(True, "sdp.c"),
            Object(True, "tpl.c"),
            Object(True, "gx_draw.c"),
            Object(True, "gx_anim.c"),
            Object(True, "usb.c"),
            Object(True, "kpad.c"),
            Object(True, "wpad.c"),
            Object(True, "wpad_mem.c"),
            Object(True, "wpad_core.c"),
            Object(True, "trk.c"),
            Object(True, "msl_c.c"),
            Object(True, "msl_cpp.c"),
            Object(True, "runtime.c"),
            Object(True, "Gecko_ExceptionPPC.c"),
        ],
    },
]

if args.mode == "configure":
    generate_build(config)
elif args.mode == "progress":
    calculate_progress(config)
